title: Sim Sim
description: "Sim Hyeon Jae"
author:
  name: "Sim Sim"
  email: "simhj316@naver.com"
  url: "https://simhj316.github.io/"

baseurl: https://simhj316.github.io/

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: false
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SimHyeonJae"
year : "2019"
